#!/usr/bin/env python3
"""Write the Android app's icons, as vector drawables, from Lucide.

The same icons the desktop window uses (docs/design/direction.md §10), drawn
the same way -- a 1.75 stroke, round caps and joins, no fill -- so the two apps
match. Only the icons named below are written; the app carries nothing else.

    npm pack lucide-static && tar -xzf lucide-static-*.tgz
    ./scripts/android-icons.py package

Each icon is android/app/src/main/res/drawable/ic_<name>.xml, dashes as
underscores, drawn in the app's secondary text colour; a view that wants
another colour tints it. Lucide draws with circles, rectangles, lines and
polylines as well as paths, and a vector drawable knows only paths, so those
are turned into path data here. Lucide is ISC-licensed; its notice is in each
file.
"""

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ICONS = """
    house folder folder-open folder-plus folder-input monitor-smartphone settings
    send arrow-up-down lock-keyhole search arrow-left ellipsis download cloud-off
    cloud check git-compare trash-2 clock rotate-ccw triangle-alert circle-alert
    x chevron-right laptop smartphone upload external-link key-round qr-code
    keyboard refresh-cw pencil copy circle-check info plus file file-text
    file-image file-video file-audio file-archive file-code hard-drive history
    save bell palette sliders-horizontal shield-check link
""".split()

OUT = Path(__file__).resolve().parent.parent / "android/app/src/main/res/drawable"

NOTICE = (
    "<!-- Generated by scripts/android-icons.py from lucide-static {version}. Do not edit.\n"
    "     Lucide, ISC License, Copyright (c) Lucide Icons and Contributors. -->\n"
)


def num(x: float) -> str:
    return f"{x:g}"


def shape_to_path(tag: str, a: dict) -> str | None:
    """The path data for one SVG shape, or None for one this cannot draw."""
    f = lambda k, d=0.0: float(a.get(k, d))
    if tag == "path":
        return a["d"]
    if tag in ("circle", "ellipse"):
        cx, cy = f("cx"), f("cy")
        rx = f("r") if tag == "circle" else f("rx")
        ry = f("r") if tag == "circle" else f("ry")
        return (f"M{num(cx - rx)},{num(cy)} a{num(rx)},{num(ry)} 0 1,0 {num(2 * rx)},0 "
                f"a{num(rx)},{num(ry)} 0 1,0 {num(-2 * rx)},0")
    if tag == "rect":
        x, y, w, h = f("x"), f("y"), f("width"), f("height")
        rx = f("rx", f("ry"))
        ry = f("ry", rx)
        if rx == 0:
            return f"M{num(x)},{num(y)} h{num(w)} v{num(h)} h{num(-w)} Z"
        return (f"M{num(x + rx)},{num(y)} H{num(x + w - rx)} A{num(rx)},{num(ry)} 0 0 1 {num(x + w)},{num(y + ry)} "
                f"V{num(y + h - ry)} A{num(rx)},{num(ry)} 0 0 1 {num(x + w - rx)},{num(y + h)} "
                f"H{num(x + rx)} A{num(rx)},{num(ry)} 0 0 1 {num(x)},{num(y + h - ry)} "
                f"V{num(y + ry)} A{num(rx)},{num(ry)} 0 0 1 {num(x + rx)},{num(y)} Z")
    if tag == "line":
        return f"M{num(f('x1'))},{num(f('y1'))} L{num(f('x2'))},{num(f('y2'))}"
    if tag in ("polyline", "polygon"):
        points = re.findall(r"-?[\d.]+", a["points"])
        pairs = [f"{points[i]},{points[i + 1]}" for i in range(0, len(points), 2)]
        return "M" + " L".join(pairs) + (" Z" if tag == "polygon" else "")
    return None


def drawable(svg: str, version: str) -> str:
    root = ET.fromstring(re.sub(r"<!--.*?-->", "", svg, flags=re.S))
    paths = []
    for el in root.iter():
        tag = el.tag.split("}")[-1]
        if tag == "svg":
            continue
        d = shape_to_path(tag, el.attrib)
        if d is None:
            raise SystemExit(f"cannot draw a <{tag}>")
        paths.append(
            "    <path\n"
            f'        android:pathData="{d}"\n'
            '        android:strokeColor="@color/text_2"\n'
            '        android:strokeWidth="1.75"\n'
            '        android:strokeLineCap="round"\n'
            '        android:strokeLineJoin="round" />'
        )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        + NOTICE.format(version=version)
        + '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp"\n'
        '    android:height="24dp"\n'
        '    android:viewportWidth="24"\n'
        '    android:viewportHeight="24">\n'
        + "\n".join(paths)
        + "\n</vector>\n"
    )


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    package = Path(sys.argv[1])
    version = re.search(r'"version":\s*"([^"]+)"', (package / "package.json").read_text()).group(1)
    for name in ICONS:
        svg = (package / "icons" / f"{name}.svg").read_text()
        (OUT / f"ic_{name.replace('-', '_')}.xml").write_text(drawable(svg, version))
    print(f"wrote {len(ICONS)} icons to {OUT}")


if __name__ == "__main__":
    main()
